// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD37NgdFh9EjSax4r1H4UrM5S6GmQ_Xg4A',
    appId: '1:585284151370:web:6304404404c3e1006b9eb3',
    messagingSenderId: '585284151370',
    projectId: 'agenda-loja',
    authDomain: 'agenda-loja.firebaseapp.com',
    storageBucket: 'agenda-loja.firebasestorage.app',
    measurementId: 'G-NP1D1KDKW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDycv6JmfaXDztDg2sOvLJ36Oguk6UdsIg',
    appId: '1:585284151370:android:0624f549874c8f1c6b9eb3',
    messagingSenderId: '585284151370',
    projectId: 'agenda-loja',
    storageBucket: 'agenda-loja.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFZpXJb9X7NZ3AIkf8zEnSUSnuvxTmECA',
    appId: '1:585284151370:ios:5e83e4af749ba41a6b9eb3',
    messagingSenderId: '585284151370',
    projectId: 'agenda-loja',
    storageBucket: 'agenda-loja.firebasestorage.app',
    iosBundleId: 'com.example.salonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFZpXJb9X7NZ3AIkf8zEnSUSnuvxTmECA',
    appId: '1:585284151370:ios:5e83e4af749ba41a6b9eb3',
    messagingSenderId: '585284151370',
    projectId: 'agenda-loja',
    storageBucket: 'agenda-loja.firebasestorage.app',
    iosBundleId: 'com.example.salonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD37NgdFh9EjSax4r1H4UrM5S6GmQ_Xg4A',
    appId: '1:585284151370:web:eaf3e75095a2d1916b9eb3',
    messagingSenderId: '585284151370',
    projectId: 'agenda-loja',
    authDomain: 'agenda-loja.firebaseapp.com',
    storageBucket: 'agenda-loja.firebasestorage.app',
    measurementId: 'G-XMB13X76KF',
  );

}